### ISSUE TITLE
Can AmpGen use PDG or EvtGen particles names instead of home-made names?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [GooFit/AmpGen#32]
Hello @tevans1260, is there a fundamental reason for AmpGen to use home-made particle names instead of well established names such as the PDG or EvtGen names? In any case, could you move to using standard names?

This matter came up again in the thread https://github.com/scikit-hep/particle/pull/354, where you can see that special code is required only because of this awkward (at least to me) convention.

Advance thanks for your replies and thoughts, as I would really like to simplify things in Particle and DecayLanguage.

**Comment by tevans1260** [comment]
HI Eduardo,

These are the 'old' PDG style names, from back when the PDG tables
contained much more information than they do now (from ... 2008 maybe?)
Unless there is something fundamentally flawed with this naming scheme
(i.e. we can't accomodate the new naming scheme for exotics) - we don't
change it - given there are a fairly large number of analyses currently
ongoing that use this (not to mention published options files, the whole
module in Gauss) i.e. reading the attached thread - the claim that
'virtually no-one is using AmpGen' is blatantly false. It may be true that
no-one is using this part of Particle, but I think that is a discussion for
between you and Henry.

That being said, I don't mind adding compatibility layers if they are not
too onerous (i.e. an option to use the PDG2014 naming), but I don't really
see what the use case for this would be (unless the PDG ever decides to
remake the more complete tables they use to publish..)

Cheers, Tim.

**Comment by eduardo-rodrigues** [comment]
There must be some confusion here. True that the PDG provided until 2008 tables with extended information; that's actually what we use in Particle to enhance the info available in recent years. But the names did not change (aside bugs or very peculiar cases). Where did you get that impression from? This is in fact the core of my query - where do the awkward names come from.

Now, that itself is not a showstopper for not making things more standard *in future versions*. Example, one can have versions o.x do something and break the API / make serious changes for versions 1.x ... For the sake of an example.

Can you point me to where you're actually using the extended PDG information, which seems to be the only reason you give for staying with old stuff

**Comment by eduardo-rodrigues** [comment]
Hello @tevans1260, can you kindly follow-up on my comments above? I'm trying to make a move towards a completion of this whole saga :-).

CC @henryiii as I see I forgot above.

**Comment by tevans1260** [comment]
@eduardo-rodrigues [with apologies,  i edited your previous comment rather than reply] 

> There must be some confusion here. True that the PDG provided until 2008 tables with extended information; that's actually what we use in Particle to enhance the info available in recent years. But the names did not change (aside bugs or very peculiar cases). Where did you get that impression from? This is in fact the core of my query - where do the awkward names come from.

Now I am unsure of what you mean by the awkward names. What we use is from the extended 2008 table, which you can find here: https://pdg.lbl.gov/2008/html/computer_read.html  (indeed, I assumed there had been a change in the more recent tables which prompted this request - upon looking them again I see that you are correct that the names are essentially the same) - so I agree there is some confusion! There are some 'custom' particles / quasiparticles that we add that are obviously not in the PDG as they are not real particles but just useful for encoding some amplitudes, for example, the notion of a generic I=0,J=0 partial wave. The other part where there are perhaps differences is how charges are handled - but these seem relatively benign. 

Could you give a specific example of where the particle names disagree? 

> Now, that itself is not a showstopper for not making things more standard *in future versions*. Example, one can have versions o.x do something and break the API / make serious changes for versions 1.x ... For the sake of an example.

It is not that you should never introduce breaking changes to APIs - but we should be hesitant - particularly when changes will break user code, then we have to weigh the benefit of changes vs annoyance, the introduction of bugs etc. As it is not clear to me what the benefit of the proposed change is (and indeed, as it turns out even exactly what the proposed change is) - I err on the side of not breaking the interface. 

> Can you point me to where you're actually using the extended PDG information, which seems to be the only reason you give for staying with old stuff

The modern tables are fairly useless (they don't even list the particle spins!). It would probably be quicker to list the properties we don't use - which would be the status and rank flags (even the quark content flags are useful for determining the ground states of a given process)

Here I hope the PDG should just goes back to providing more complete tables (or more accurately, actually releases the complete tables, as looking back at the history they never went out of the 'experimental' phase) I hope the existence of the particle package encourages this!

**Comment by eduardo-rodrigues** [comment]
Hey, thanks a lot for the replies. I will try and reply soon ... Just 2 comments for now:

> The modern tables are fairly useless (they don't even list the particle spins!). It would probably be quicker to list the properties we don't use - which would be the status and rank flags (even the quark content flags are useful for determining the ground states of a given process)

The info "a la 2008" is what the Particle package uses ;-). You could profit from it for free.

I believe you are at CERN? We should just have a tea/coffee together and walk through this ...

**Comment by eduardo-rodrigues** [comment]
> Could you give a specific example of where the particle names disagree?

Sure, take for example the few names we have tested in `Particle`:
```
In [11]: for name_ampgen, pdgid in ampgen_style_names:
    ...:     print(f"{pdgid}:\t AmpGenname={name_ampgen:20s} PDG name={Particle.from_pdgid(pdgid).name:15s}")
    ...:
5:       AmpGenname=b                    PDG name=b
-5:      AmpGenname=b~                   PDG name=b~
211:     AmpGenname=pi+                  PDG name=pi+
-211:    AmpGenname=pi-                  PDG name=pi-
-313:    AmpGenname=K~*0                 PDG name=K*(892)~0
-313:    AmpGenname=K*(892)bar0          PDG name=K*(892)~0
20213:   AmpGenname=a(1)(1260)+          PDG name=a(1)(1260)+
100113:  AmpGenname=rho(1450)0           PDG name=rho(1450)0
113:     AmpGenname=rho(770)0            PDG name=rho(770)0
-10323:  AmpGenname=K(1)(1270)bar-       PDG name=K(1)(1270)-
-325:    AmpGenname=K(2)*(1430)bar-      PDG name=K(2)*(1430)-
```
You can clearly see some trend in how you write names.

> It is not that you should never introduce breaking changes to APIs - but we should be hesitant - particularly when changes will break user code, then we have to weigh the benefit of changes vs annoyance, the introduction of bugs etc. As it is not clear to me what the benefit of the proposed change is (and indeed, as it turns out even exactly what the proposed change is) - I err on the side of not breaking the interface.

I totally buy the argument of balancing pros and cons. But I would hope that the code is basically agnostic to particle names except in a very few places where the name string actually matters, right? I am still waiting for you to point me to where you manipulate names, to understand how much would need to be changed, I think for a better package since relying on fully supported and accepted names. This is a non-negligible benefit IMO to follow conventions pretty much anyone else follows. See also my comment below ...

> The modern tables are fairly useless (they don't even list the particle spins!). It would probably be quicker to list the properties we don't use - which would be the status and rank flags (even the quark content flags are useful for determining the ground states of a given process)

I wouldn't say that. They contain a lot of info already, just not some of the info that is crucial for your use-case.

I repeat my comment that all the extra info you list and need is what the Particle package has been providing to many people since years, in a maintained package ;-). Why not simply profit from it?

> Here I hope the PDG should just goes back to providing more complete tables (or more accurately, actually releases the complete tables, as looking back at the history they never went out of the 'experimental' phase) I hope the existence of the particle package encourages this!

I have been in discussions with them in the early days. Can tell you more ... Actually, can we talk at CERN since both around? Seems easier/best. Thanks.

**Comment by eduardo-rodrigues** [comment]
If you fancy a comparison with EvtGen names, here it is:
```
In [1]: ampgen_style_names = (
   ...:     ("b", 5),
   ...:     ("b~", -5),
   ...:     ("pi+", 211),
   ...:     ("pi-", -211),
   ...:     ("K~*0", -313),
   ...:     ("K*(892)bar0", -313),
   ...:     ("a(1)(1260)+", 20213),
   ...:     ("rho(1450)0", 100113),
   ...:     ("rho(770)0", 113),
   ...:     ("K(1)(1270)bar-", -10323),
   ...:     # ("K(1460)bar-", -100321),
   ...:     ("K(2)*(1430)bar-", -325),
   ...: )

# ...

In [12]: for name_ampgen, pdgid in ampgen_style_names:
    ...:     print(f"{pdgid}:\t AmpGenname={name_ampgen:20s} PDG name={Particle.from_pdgid(pdgid).name:15s} EvtGen name={Particle.from_pdgid(pdgid).evtgen_name:15s}")
    ...:
5:       AmpGenname=b                    PDG name=b               EvtGen name=b
-5:      AmpGenname=b~                   PDG name=b~              EvtGen name=anti-b
211:     AmpGenname=pi+                  PDG name=pi+             EvtGen name=pi+
-211:    AmpGenname=pi-                  PDG name=pi-             EvtGen name=pi-
-313:    AmpGenname=K~*0                 PDG name=K*(892)~0       EvtGen name=anti-K*0
-313:    AmpGenname=K*(892)bar0          PDG name=K*(892)~0       EvtGen name=anti-K*0
20213:   AmpGenname=a(1)(1260)+          PDG name=a(1)(1260)+     EvtGen name=a_1+
100113:  AmpGenname=rho(1450)0           PDG name=rho(1450)0      EvtGen name=rho(2S)0
113:     AmpGenname=rho(770)0            PDG name=rho(770)0       EvtGen name=rho0
-10323:  AmpGenname=K(1)(1270)bar-       PDG name=K(1)(1270)-     EvtGen name=K_1-
-325:    AmpGenname=K(2)*(1430)bar-      PDG name=K(2)*(1430)-    EvtGen name=K_2*-
```

CC @henryiii and @jonas-eschle who have been in the discussions in the Scikit-HEP packages.

**Comment by tevans1260** [comment]
So the difference is exclusively in how 'bar' is handled vs tilde. As I said before, this seems extremely benign. ~ is also not a great choice of symbol (bar is not great either) - but frankly I don't really care either way. The 'bar' on the charged particles is particuarly annoying and unnecessary but is actually in the prescribed names in the 2008 PDG for some reason (its column 84) 

In fact, looking at the documentation, we follow that standard exactly, as the use of the 'bar' to indicate the antiparticle:

               A = F     - particle that has anti-particle partner different from particle
                           with ascii name formed by concatenation of the name shown below with string 'bar' and charge
                          by the rule (nu(e) <--> nubar(e), p <--> pbar, Delta++ <--> Deltabar--)

The names are the primary part of the interface. I.e. models are written as  D0{pi+,pi-}, D0{K(1)(1270)bar-,K+} etc. 
Changing the names (or at least, dropping support for the existing names) breaks a large number of these models that are out in the wild, so no we cannot just make this change without incurring a significant amount of work and breaks to a large amount of user code.   

I also note something is wrong in your AmpGen names, as you have two different things for =313 i.e. K*(892)[bar,0]0. 

The actual change inside AmpGen is obviously not difficult - but this was never said to be the problem.. 

I'm closing this issue as I don't think we are going to agree. If you wish to discuss in person perhaps we can in a few weeks.

**Comment by eduardo-rodrigues** [comment]
At least the message is clear that you do not care about support for AmpGen in the `Particle` package, nor you are interested in using it. OK, clear.
